---
- name: metrics-server
  hosts: master1
  gather_facts: no

  vars:
    ansible_become_pass: "ccma"

  tasks:
    - name: Synchronization of src on the control machine to dest on the remote host 
      synchronize: 
        src: metrics-server
        dest: /home/ccma

    - name: Deploy metrics-server in the cluster
      shell: "kubectl create -f deploy/1.8+/"
      args:
        chdir: /home/ccma/metrics-server
      register: create_metrics_server

    - name: Debug create_metrics_server
      debug:
        var: create_metrics_server
